# -*- coding: utf-8 -*-
"""ProjetoInterface.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u15R_MnV-vNvZu0-MW-HJmYVP-6ZG067
"""

nome = input("Como gostaria de ser chamada(o)? ")
categorias = ["Wordpress", "Criação de Site","E-commerce","Marketing Digital","Vendas","Google Ads","Design","Negócios","Youtube","Criação de Conteúdo","Programação"]
for i in range (len(categorias)):
  #equivalente a usar enumerate
  print(f"{i}. {categorias[i]}")

num_das_categorias = input("\nDigite o número dos assuntos de seu interesse (use vírgulas):")

tempo = int(input("\nQuanto tempo gostaria de estudar? (minutos) "))

mostrar_premium = input("\nMostrar cursos Premium? (S/N)")

if mostrar_premium == "N" or mostrar_premium == "n":
  mostrar_premium = False
else:
  mostrar_premium = True

num_das_categorias = num_das_categorias.split(",")
ncategorias = []
for elemento in num_das_categorias:
  numero = int(elemento.strip())
  ncategorias.append(numero)

print(f"\nNome: {nome}")
print(f"ID das Categorias: {ncategorias}")
print(f"Tempo: {tempo}")
print(f"Premium?: {mostrar_premium}")

cursos = ["Introdução ao Wordpress", "Criador de Sites", "Introdução ao WooCommerce","Afiliado de Sucesso", "Venda mais com WhatsApp Business","Introdução ao Google Ads", "E-commerce e Vendas Online","Canva: Design Fácil para Empresas","Youtube para Iniciantes","Rede de Display e Youtube","Desenvolvimento de Plugins"]

tempos = [95,25,35,85,75,150,140,120,85,335,160]

categorias_do_curso = [['wordpress','criação de sites'], ['criação de sites'],['e-commerce','criação de sites','wordpress'],['marketing digital','vendas'],['marketing digital','vendas','google ads'],['marketing digital','google ads'],['e-commerce','vendas','negócios'],['design','negócios'],['youtube','criação de conteudo'],['marketing digital','google ads','youtube'],['programação','wordpress']]

gratuidade = [True,True,True,True,True,True,True,True,True,False,True]

categorias_selecionadas = []
for n in ncategorias:
  categorias_selecionadas.append(categorias[n].upper())

print(f"\nOlá, {nome}, com base no seu perfil, achamos que você iria gostar dos seguintes cursos:")

for cat in categorias_selecionadas:
  print(f"{cat}:")
  for linha in range(len(cursos)):
    if gratuidade[linha] or mostrar_premium:
      if (cat.lower() in categorias_do_curso[linha]
         and tempos[linha] <= tempo):
        print(f"- {cursos[linha]} ({tempos[linha]} min)")